# Generated by Django 4.2.6 on 2023-10-14 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Default",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sugar_delta_max", models.FloatField(default=10.0)),
                ("sugar_delta_min", models.FloatField(default=1.0)),
                ("sugar_morning_max", models.FloatField(default=10.0)),
                ("sugar_morning_min", models.FloatField(default=1.0)),
                ("sugar_evening_max", models.FloatField(default=10.0)),
                ("sugar_evening_min", models.FloatField(default=1.0)),
                ("sugar_before_max", models.FloatField(default=10.0)),
                ("sugar_before_min", models.FloatField(default=1.0)),
                ("sugar_after_max", models.FloatField(default=10.0)),
                ("sugar_after_min", models.FloatField(default=1.0)),
                ("systolic_max", models.IntegerField(default=10)),
                ("systolic_min", models.IntegerField(default=1)),
                ("diastolic_max", models.IntegerField(default=10)),
                ("diastolic_min", models.IntegerField(default=1)),
                ("pulse_max", models.IntegerField(default=10)),
                ("pulse_min", models.IntegerField(default=1)),
                ("weight_max", models.FloatField(default=10.0)),
                ("weight_min", models.FloatField(default=1.0)),
                ("bmi_max", models.FloatField(default=10.0)),
                ("bmi_min", models.FloatField(default=1.0)),
                ("body_fat_max", models.FloatField(default=10.0)),
                ("body_fat_min", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("after_recording", models.BooleanField(default=False)),
                ("no_recording_for_a_day", models.BooleanField(default=False)),
                ("over_max_or_under_min", models.BooleanField(default=True)),
                ("after_meal", models.BooleanField(default=True)),
                ("unit_of_sugar", models.BooleanField(default=True)),
                ("unit_of_weight", models.BooleanField(default=True)),
                ("unit_of_height", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Weight",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("weight", models.FloatField()),
                ("bmi", models.FloatField()),
                ("body_fat", models.FloatField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("birthday", models.DateField(null=True)),
                ("height", models.FloatField(default=0.0)),
                ("gender", models.BooleanField(default=True)),
                ("fcm_id", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("weight", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "default",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.default",
                    ),
                ),
                (
                    "setting",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.setting",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Medical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diabetes_type", models.IntegerField(default=1)),
                ("oad", models.BooleanField(default=True)),
                ("insulin", models.BooleanField(default=True)),
                ("anti_hypertensives", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("type", models.IntegerField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Diet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=100)),
                ("meal", models.IntegerField()),
                ("tag", models.CharField(max_length=100)),
                ("image", models.IntegerField()),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Care",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reply_id", models.IntegerField(default=0)),
                ("message", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BloodSugar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sugar", models.FloatField()),
                ("timeperiod", models.IntegerField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("drug", models.IntegerField()),
                ("exercise", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BloodPressure",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("systolic", models.IntegerField()),
                ("diastolic", models.IntegerField()),
                ("pulse", models.IntegerField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="A1c",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("a1c", models.IntegerField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
