# Generated by Django 4.2.6 on 2023-10-11 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_default_bmi_max_alter_default_bmi_min_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="setting",
            old_name="after_recoding",
            new_name="after_recording",
        ),
    ]
