# Generated by Django 4.2.6 on 2023-10-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_weight_bloodsugar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodpressure",
            name="id",
        ),
        migrations.RemoveField(
            model_name="bloodsugar",
            name="id",
        ),
        migrations.RemoveField(
            model_name="weight",
            name="id",
        ),
        migrations.AddField(
            model_name="bloodpressure",
            name="UID",
            field=models.AutoField(default=10787, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bloodsugar",
            name="UID",
            field=models.AutoField(default=6466, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weight",
            name="UID",
            field=models.AutoField(default=3846, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
