# Generated by Django 4.2.6 on 2023-10-11 04:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auth",
            old_name="activated",
            new_name="verified",
        ),
    ]
